### ISSUE TITLE
Credits and license tracking

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Android-Development#13]
@valdio please add here the licenses of the different libraries (or other elements) used for the developed.

**Comment by rskikuli** [comment]
@valdio I think it's better to add the licenses here: https://github.com/CityZenApp/CityZen-Android/wiki/Copyright-info. It is a wiki for the project I created. Hopefully it will help us having better documentation.

**Comment by valdio** [comment]
# Libraries used in the app:

### Android support libraries:

com.android.support:appcompat-v7:25.3.1 
com.android.support:design:25.3.1
com.android.support:recyclerview-v7:25.3.1
com.android.support:cardview-v7:25.3.1
com.android.support:support-vector-drawable:25.3.1
com.android.support:support-v4:25.3.1
com.android.support.constraint:constraint-layout:1.0.2
Apache License 2.0
https://android.googlesource.com/platform/frameworks/support.git/+/8c2c698fb9691244fe00319e37400245f4a5b9f2/LICENSE.txt


de.westnordost:osmapi:1.6
GNU Lesser General Public License v3.0
https://github.com/westnordost/osmapi/blob/master/LICENSE


info.metadude.java.library.overpass:overpass-library:2.0.0
Apache License 2.0
https://github.com/johnjohndoe/Overpass/blob/master/LICENSE.txt


oauth.signpost:signpost-core:1.2.1.2
Apache License 2.0
https://mvnrepository.com/artifact/oauth.signpost/signpost-core/1.2.1.2


org.osmdroid:osmdroid-android:5.6.4
Apache License 2.0
https://github.com/osmdroid/osmdroid/blob/master/LICENSE


com.github.MKergall:osmbonuspack:6.3
GNU Lesser General Public License v3.0
https://github.com/MKergall/osmbonuspack/blob/master/LICENSE.md

com.google.code.gson:gson:2.7
Apache License 2.0
https://mvnrepository.com/artifact/com.google.code.gson/gson/2.7


com.github.clans:fab:1.6.4
Apache License 2.0
https://github.com/Clans/FloatingActionButton/blob/master/LICENSE

com.github.ittianyu:BottomNavigationViewEx:1.1.7
MIT License
https://github.com/ittianyu/BottomNavigationViewEx/blob/master/LICENSE.txt


pub.devrel:easypermissions:0.4.0
Apache License 2.0
https://github.com/googlesamples/easypermissions/blob/master/LICENSE

**Comment by rskikuli** [comment]
Thank you @valdio. The license notes will be reflected on [www.cityzenapp.co](www.cityzenapp.co) in the next days. Closing this issue now.
