### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Android-Development#14]
In many cases search doesn't display any results. A 'no results found' message with ideally a related image needs to be displayed.

**Comment by rskikuli** [comment]
This is what we discussed about on the January meetup at our hackerspace in Tirana @AnXh3L0. Can you pass to @sidorelauku a design of how the screen should look like?

**Comment by AndyScherzinger** [comment]
@rskikuli imho fixed already via #58

**Comment by sidorelauku** [comment]
Thanks @AndyScherzinger  the PR is merged.
