### ISSUE TITLE
Search functionality bug

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Android-Development#15]
The search functionality on the Alpha Version of the software doesn't work on many devices.
This is a comment from [this bug](https://github.com/CityZenApp/CityZen-Android/issues/3) - thanks. Creating a dedicated bug since it is an important feature. Search is not functional as reported by @kokushta and other users.

**Comment by Sidorela24** [comment]
Testing the app I also have the same problem the search button still doesn't work. 
I wanted to add that when location is enabled, search gives an empty result.
While when location isn't enabled and I tried to search, the app craches.

**Comment by rskikuli** [comment]
Adding this to v. 1.2.

**Comment by rskikuli** [comment]
Closing this as it is a duplicate from #14
