### ISSUE TITLE
Add zoom buttons in the map

### ISSUE THREAD

**Issue by jbelien** [CityZenApp/Android-Development#22]
I usually use my phone with one hand ;
Would be really useful to have a zoom +/- button in the map.

I know to zoom I just have to double-tap the screen (and it works really well) but to unzoom a button would be convenient I think !

**Comment by rskikuli** [comment]
This is now on the list of features for the next release. Thank you for submitting the issue. I'll close this once your proposal is implemented in the new version(s).

**Comment by sidorelauku** [comment]
Included in PR #84
