### ISSUE TITLE
Convenience store as part of supermarket category

### ISSUE THREAD

**Issue by Sidorela24** [CityZenApp/Android-Development#23]
Other categories and POIs can be added, while testing I am trying to figure out whats missing. 
I find super market category resulting with a few POIs because it includes only features of tag shop:super market. 
What about showing also mini-markets , POI type shop: [convenience](https://wiki.openstreetmap.org/wiki/Tag:shop=convenience) ?

**Comment by rskikuli** [comment]
Thank you for your contribution @Sidorela24 . Adding your proposal here: https://github.com/CityZenApp/CityZen-Android/wiki/Scrapbook. I will close this issue once it is added on the next release.

**Comment by rskikuli** [comment]
@Sidorela24 this is now added on the v1.0 of the app. Please confirm that this is working so that I close this 'issue'. Thank you.

**Comment by Sidorela24** [comment]
Hey @rskikuli, yes it works now. 
Thank you.
