### ISSUE TITLE
Add ability to sign up on OSM using CityZen App

### ISSUE THREAD

**Issue by Borisbudini** [CityZenApp/Android-Development#26]
I was wondering if the ability to sign up for OSM using CityZen App is possible. This popup can be shown along with sign in

**Comment by rskikuli** [comment]
If you go to a Point of Interest @Borisbudini you can log in to your OSM account easily with a pop up. Please check it and let me know if it is not working. 
ps: thank you for your contribution :) 
.

**Comment by Borisbudini** [comment]
Hey Redon. What i meant was to create an account, not log in.On Sep 10, 2017 17:29, Redon Skikuli <notifications@github.com> wrote:If you go to a Point of Interest @Borisbudini you can log in to your OSM account easily with a pop up. Please check it and let me know if it is not working.
ps: thank you for your contribution :)
.

**Comment by jbelien** [comment]
I don't think it's possible.
And I'm not sure it's a good idea actually, you shouldn't hijack the registration process from osm.org ; everything linked to OSM depends on OAuth.

I would rather add a link to load the registration page (https://www.openstreetmap.org/user/new) or open that page in a popup (don't know if it's possible).

**Comment by rskikuli** [comment]
@Borisbudini I agree with @jbelien on this. In any case we have added log-in and log out functions on te new version now. Closing this issue. Thank you guys for the input.
