### ISSUE TITLE
Category BikeRoad

### ISSUE THREAD

**Issue by shehuceljeta** [CityZenApp/Android-Development#28]
Hello,
Could you add another category within my repository (https://github.com/shehuceljeta/Android-Development)? 
The name of category:BikeRoad, icon: a bicycle. In this category will be display all the bicycle road in Albania(tag: highway=cycleway).(Like the logic of Transportation menu)
According to the location that user want to go, the app will display the road that must be followed in a map.
Thank you.

**Comment by rskikuli** [comment]
@shehuceljeta first of all thank you for getting involved with our project. After talking with @valdio it seems that this feature is quite complicated to be implemented at the moment, but it is a good idea for the next releases. Closing this issue.
