### ISSUE TITLE
Results missing on categories even when they are on the map

### ISSUE THREAD

**Issue by Sidorela24** [CityZenApp/Android-Development#29]
Ass I mentioned on [issue 24](https://github.com/CityZenApp/Android-Development/issues/24) when I search on an category it donesn't give me all the results. I saw from the code that the radius was 600m. From the screenshot I am showing where a hotel is( green color) and where I'm (red color) also because the routing is not functioning right now. 
Category hotel/hostel only shows me one hotel which is twice as far as this one. I see the problem from filtering results, because on the code it only searches for a single point, while this hotel (and other properties also) is not mapped as a single point but as an area which means there is more than a pair of coordinates (longitude,latitude). 

![cityzen2bug](https://user-images.githubusercontent.com/24439184/30533927-22bcb73c-9c5c-11e7-8665-0538bc7ce2e4.jpg)
![cityzen1bug](https://user-images.githubusercontent.com/24439184/30533928-22c0360a-9c5c-11e7-9946-c5c876cd91d7.jpg)

**Comment by rskikuli** [comment]
This should have been fixed now. Please confirm @Sidorela24 so that I close this issue. Thanks!

**Comment by rskikuli** [comment]
Closing this as it is a duplication of issue #24.
