### ISSUE TITLE
First test

### ISSUE THREAD

**Issue by kokushta** [CityZenApp/Android-Development#3]
First let me congratulate you for creating and working on such projects. Please read carefully everything. I am pointing out my experience.

Lenovo Vibe Z2
Android 4.4.4
Quad-core 1.2GHz
RAM/MEMORY: 2GB / 32GB

Installation: no issues

Running:
It is slow. Sometimes it crashes. 

Functions:

SEARCH
Search is not functional or I cannot figure out what the result should be. 
Say, I click on Restaurants, and I get Stela. If I search for Stela, results come empty. A message like "no data" or "search term not found" can help users understand if the search function is working or not.

DIRECTIONS
Direction not good. I click on Restaurants, and I get Stela. Then I click on Getting directions and it shows a straight line from point A to B. Not good.

![cityzen-get-direction](https://user-images.githubusercontent.com/1438037/29268664-119bb838-80ee-11e7-8487-1233d41dcdc4.jpg)

**Comment by rskikuli** [comment]
Thanks @kokushta for the feedback. I'm splitting the comments in separate issues since there are different bugs that need different approach in terms of debugging. Again thanks for the feedback.

**Comment by rskikuli** [comment]
@kokushta please download the v1.0 of the app from [Fdroid repository](https://fdroid.gitlab.io/fdroid-website/packages/com.cityzen.cityzen/) and let me know if everything works now. If yes I'll close this issue. Thanks for taking the time to test the app.

**Comment by rskikuli** [comment]
@kokushta any news on this? Please download the latest version here: http://cityzenapp.co/ and report if the issues mentioned have been improved. Thank you.

**Comment by rskikuli** [comment]
I have extensively tested this and it seems that with the latest version of the app everything works. Please comment on this issue if you still have this issue @kokushta . Thank you for your contribution. Closing this.
