### ISSUE TITLE
Display of the address

### ISSUE THREAD

**Issue by jbelien** [CityZenApp/Android-Development#32]
You display the name of the place in the address field in the information "popup".
I think it's a bit confusing ! 

Look at the screenshots here under, 
- the first one is quite okay (even though the place name is repeated twice, which is not necessary) but 
- the second one only display the name as the address, which does not make any sense.

Also in Belgium (and lots of other countries), we need the house number of the place ; the street is not enough to find (easily) the place.

![screenshot_20170926-140717](https://user-images.githubusercontent.com/1150563/30859601-b222d348-a2c4-11e7-8180-4506f4309002.png)
![screenshot_20170926-140725](https://user-images.githubusercontent.com/1150563/30859600-b220d002-a2c4-11e7-99b6-ecbde4504017.png)

**Comment by AndyScherzinger** [comment]
Also saw this display issue. I am on it, PR to be opened soon :)

**Comment by AndyScherzinger** [comment]
PR is #70
