### ISSUE TITLE
Share Address With Other Apps

### ISSUE THREAD

**Issue by cwmke** [CityZenApp/Android-Development#34]
I think it could be useful to add a share option to send the selected poi to another app. For example, OsmAnd for navigation or a chat app to share your location with a friend.

**Comment by rskikuli** [comment]
Very good point @cwmke. This is definitely going to the list of features for the next release! Thanks for taking the time to add your proposal.

**Comment by AndyScherzinger** [comment]
PR #83 contains a share option for geo-links recognized by map applications
