### ISSUE TITLE
Stores with no openning time shouldn't disapear when looking for opened store

### ISSUE THREAD

**Issue by Dostoi** [CityZenApp/Android-Development#42]
When you check the option to show only open store, stores with no opening time disappear along with the closed one's. It's not because you don't have its time that it's closed.
Instead they should be showed but under the ones that we are sure are open.

**Comment by rskikuli** [comment]
Thanks for taking the time to propose this @Dostoi. This is indeed something that makes sense to be in the next release along with some other improvements we are planning at the moment. Adding this to the list of labels with feature proposals. Thank you.

**Comment by AndyScherzinger** [comment]
PR is #75
