### ISSUE TITLE
Emptycontent view for favorites

### ISSUE THREAD

**Issue by jancborchardt** [CityZenApp/Android-Development#46]
On initial start, or when you don’t have any favorites yet, the view is completely empty. It looks a bit like an error, or things didn’t load.

For proper feedback, an empty state is great. Also see http://emptystat.es/

This is for example how we do it in Nextcloud:
![screenshot from 2017-11-10 12-54-17](https://user-images.githubusercontent.com/925062/32657557-85175958-c616-11e7-86a2-c72dc5a92956.png)

**Comment by rskikuli** [comment]
@AnXh3L0 did you find the time to proceed with this? Thanks.

**Comment by AndyScherzinger** [comment]
@rskikuli this has been fixed and merged via #61

**Comment by sidorelauku** [comment]
Issue fixed, I'm going to close this.
