### ISSUE TITLE
Translation of URL's and email address

### ISSUE THREAD

**Issue by jbelien** [CityZenApp/Android-Development#49]
I started to translate CityZenApp in French (https://hosted.weblate.org/projects/cityzen/strings/fr/) and I noticed that URL's and email address are in the words to translate ... but that doesn't make any sense to translate those.

For instance (in [`strings.xml` file](https://github.com/CityZenApp/Android-Development/blob/master/CityZenApp/app/src/main/res/values/strings.xml)) :
```
<string name="domain">www.cityzenapp.co</string>
<string name="license_link">www.cityzenapp.co/license</string>
<string name="privacy_policy_link">www.cityzenapp.co/app-privacy-policy</string>
<string name="email_contact">ping@cityzenapp.co</string>
...
<string name="get_involved_link">www.github.com/CityZenApp</string>
...
<string name="credits_link">www.cityzenapp.co/credits</string>
```

IMHO those strings have nothing to do in that file and could be "hardocded" in the code.

**Comment by AndyScherzinger** [comment]
PR is #69 in case the translation system respects Android's `translatable="false"` flag
