### ISSUE TITLE
Slow osm loading 

### ISSUE THREAD

**Issue by diskmanti** [CityZenApp/Android-Development#5]
Sometimes the osm base layer is slow on downloading. Tried it on 4g and wifi network. It does not happen all the time tho

**Comment by rskikuli** [comment]
@diskmanti, unfortunately this is due to many factors that are not related to us. For example, OSM map loading times, device used and of course the mobile network. Fortunately, we are having only a few reports like this at this early stage of testing.

**Comment by rskikuli** [comment]
@diskmanti please test the latest v1.0 as released on Fdroid platform and check if you are having the same issues. This could help us understand the issues better. Thank you.

**Comment by diskmanti** [comment]
Hello,
I am using a General Mobile 4g,pure Android device. From my test today it looks faster than before. It seems the app downloads the tiles first and cashes them for further use. This makes the app load the map faster after the first few moments. I think it is better now and should not be an issue for most of the users.

Cheers

**Comment by rskikuli** [comment]
Thank you @diskmanti  for your feedback. Closing this since it is now improved.

**Comment by kominoshja** [comment]
Test
