### ISSUE TITLE
Search page needs new design

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Android-Development#52]
The search page needs e new design and UX design since now it is really confusing. The Nextcloud app is a good example as an approach. See #46 for better understanding.  The 'nothing found' message should be fun and clear.

**Comment by AndyScherzinger** [comment]
I implemented this for the Nextcloud Android App. Let me know if you need any pointers, hint, help or anything :) Happy to help!

**Comment by rskikuli** [comment]
@AndyScherzinger can you share the source files here if they are on a CC licene? We are working the working on ver. 1.0 and that would really help :).

**Comment by AndyScherzinger** [comment]
The source files are basically Android files (XML, java), but is it quite "easy"
The "empty view" can be seen here: https://github.com/nextcloud/android/blob/master/src/main/res/layout/empty_list.xml
and
java-wise
https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/ui/activity/ActivitiesListActivity.java#L346

The code is all GPL3 though but like I said I can help out and could do a PR if you can give me some pointers where this should be integrated :)

**Comment by AndyScherzinger** [comment]
@rskikuli I opened a PR to provide a sample implementation of how this can be done. It is a working implementation. #58

**Comment by AndyScherzinger** [comment]
@rskikuli @AnXh3L0 @jancborchardt @sidorelauku one question about the favorites empty page design should the "heart" icon be grey or like we do it for favorites in the Nextcloud app be colored (semitransparent)?
