### ISSUE TITLE
Launch of v1.1.0 on F-droid

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Android-Development#57]
Let's work on launching v1.1 on F-Droid. Goal: 15.03.2018. Tasks:

- remaining changes implementation https://github.com/CityZenApp/Android-Development/issues?q=is%3Aopen+is%3Aissue+label%3A%22ver+1.1%22
- documentation of improvements on OSM wiki page of CityZen;
- blog post for our website (press release);
- follow the F-droid procedure to update.

**Comment by rskikuli** [comment]
- @jbelien and/or @AndyScherzinger can you help us with a release candidate v 1.1.0 similar to this one https://github.com/grote/Transportr/commit/c40d3cc9429b3e5c986fdf4961d3742c79307fc0? 
- @marianaballa can we work together on a blog post featuring a list of changes? 
- @sidorelauku presence on OSM wiki?
- @jbelien do you remember the steps to send it to Fdroid?

**Comment by jbelien** [comment]
> @jbelien and/or @AndyScherzinger can you help us with a release candidate v 1.1.0 similar to this one grote/Transportr@c40d3cc?

You just have to create a new release here on GitHub (and upload the APK) : https://github.com/CityZenApp/Android-Development/releases.

> @jbelien do you remember the steps to send it to Fdroid?

If I remember correctly, you just have to publish a release here on GitHub to "publish" it automatically on FDroid :)

**Comment by AndyScherzinger** [comment]
I commited ethe right version number to master, so now whenever you build master it'll be 1.1.0RC1

**Comment by rskikuli** [comment]
@nafieshehu and @sidorelauku will work on this this week. Ideal deadline: 6.04.2018.

**Comment by sidorelauku** [comment]
@AndyScherzinger  as I found it difficult to upgrade manually to the next version. I think it woul be better to keep the same way of versioning as the begining. What do you think?

**Comment by AndyScherzinger** [comment]
@sidorelauku if it makes things easier for you to release new versions, sure thing :+1:

**Comment by AndyScherzinger** [comment]
So now I guess we just need to tag a release `v1.1.0` and wait, is there anything that needs to be done before? @sidorelauku @rskikuli ?

**Comment by AndyScherzinger** [comment]
Tag has been created and f-droid PR has been commented so now let's wait for f-droid to pick it up :)
