### ISSUE TITLE
Change of name at OpenStreetMap editing name of the app

### ISSUE THREAD

**Issue by rskikuli** [CityZenApp/Android-Development#6]
When editing with CityZen app at OpenStreetMap changeset it shows that the contribution has been made using 'CityZen'. I think would be more accurate if the name of the app would appear as 'CityZen Android app'.
![screenshot from 2017-08-17 01-18-36](https://user-images.githubusercontent.com/17770262/29389560-239408e8-82eb-11e7-8a74-3fa0f595124f.jpg)

**Comment by jbelien** [comment]
Maybe add the version of the app in `created_by` tag too (see https://wiki.openstreetmap.org/wiki/Key:created_by) !

**Comment by rskikuli** [comment]
Thanks @jbelien. We will use 'CityZen Android app v.1.0' based also on your comment. Ping @valdio.

**Comment by rskikuli** [comment]
@jbelien this should have been fixed with the v1.0 of the app release on Fdroid. Can you please confirm? Also is this related somehow with [issue #35](https://github.com/CityZenApp/Android-Development/issues/35) in your opinion?

**Comment by jbelien** [comment]
Confirmed : `created_by: CityZen Android app v.1.0` !
I would remove the dot (`.`) between the `v` and the first digit of the version though (`1`) to make `v1.0`.

Issue #35 is not related to this :)

**Comment by rskikuli** [comment]
@sidorelauku please change the new version to CityZen Android app v1.1.

**Comment by AndyScherzinger** [comment]
PR is #71
